#ifndef _IO_CTRL_CODE_H_
#define _IO_CTRL_CODE_H_

#define		IOCTRL_FAST_MUTEX		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define		IOCTRL_START_TIMER		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define		IOCTRL_STOP_TIMER		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#endif
